source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'CSQuiz.xcodeproj'

use_frameworks!

platform :ios, '9.0'

# 3rd party
pod 'Alamofire', :inhibit_warnings => true
pod 'SVProgressHUD', :inhibit_warnings => true
pod 'SwiftyJSON', :inhibit_warnings => true

# Public - Mirego
pod 'MCDateExtensions', :git => 'git@github.com:mirego/MCDateExtensions.git', :inhibit_warnings => true
pod 'MCUIColorUtils', :git => 'git@github.com:mirego/MCUIColorUtils.git', :inhibit_warnings => true
pod 'MCUIViewLayout', :git => 'git@github.com:mirego/MCUIViewLayout.git', :inhibit_warnings => true
pod 'MRGArchitect', :git => 'git@github.com:mirego/MRGArchitect.git', :inhibit_warnings => true
