source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'RebelChat.xcodeproj'

use_frameworks!

platform :ios, '9.0'

# 3rd party
pod 'Alamofire', :inhibit_warnings => true
pod 'SVProgressHUD', :inhibit_warnings => true
pod 'SwiftyJSON', :inhibit_warnings => true

# Public - Mirego
pod 'MCUIColorUtils', :git => 'https://github.com/mirego/MCUIColorUtils.git', :inhibit_warnings => true
pod 'MCUIViewLayout', :git => 'https://github.com/mirego/MCUIViewLayout.git', :inhibit_warnings => true
pod 'MRGArchitect', :git => 'https://github.com/mirego/MRGArchitect.git', :inhibit_warnings => true
